In [28]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [29]:
# Drop unneeded columns
raw_df = pd.read_csv("../res/responses.csv")
raw_df.drop(["Timestamp", "Name (Optional)"], axis=1, inplace=True);

In [30]:
# Change column names
cols = raw_df.columns
new_cols = []
for col in cols:
    try:
        new_cols.append(col[col.index("[")+1:-1])
    except ValueError:
        new_cols.append(col)
raw_df.columns = new_cols

to_replace = {
    "Would you agree that you frequently shop online?":"Frequency",
    "Where do you shop more often?":"Where",
    "BACK TO SCHOOL - Please select all items that you would typically buy during this season.":"Back To School",
    "SUMMER - Please select all items that you would typically buy during this season.":"Summer",
    "Home Entertainment (TV, Speakers, Online Streaming Subscription, Etc.)":"Home Entertainment",
    "Current Region ":"Current Region"
}
raw_df.rename(columns = to_replace, inplace = True)

raw_df.columns

Index(['Age', 'Gender', 'Marital Status', 'Employment Status',
       'Current Region', 'Frequency', 'Where', 'Apparel/Clothing',
       'Health & Personal Care', 'Home Entertainment', 'Babies & Kids',
       'Food/Groceries', 'Toys, Games, Collectibles', 'Bags', 'Stationery',
       'Books', 'Sports & Travel', 'Wearable Accessories',
       'Automobile Accessories', 'Cameras/Camera Accessories',
       'Laptops/Computers', 'Tech Accessories', 'Pet Care/Accessories',
       'Power Tools', 'Back To School', 'Summer'],
      dtype='object')

In [31]:
# Create baskets according to season

user_data_cols = ['Age', 'Gender', 'Marital Status', 'Employment Status', 'Current Region', 'Frequency', 'Where']

# Create baskets for xmas, new year, when needed
holidays_basket = raw_df.drop(["Summer", "Back To School"], axis=1);
bdays_basket = raw_df.drop(["Summer", "Back To School"], axis=1);
periods_basket = raw_df.drop(["Summer", "Back To School"], axis=1);
wneeded_basket = raw_df.drop(["Summer", "Back To School"], axis=1);
seasonal_baskets = [holidays_basket, bdays_basket, periods_basket, wneeded_basket]

# Change values accordingly
keywords = ["Christmas", "Birthdays", "Monthly", "Needed"]
i = 0
for basket in seasonal_baskets:
    cols = basket.columns
    keyword = keywords[i]
    for col in cols:
        if col not in user_data_cols:
            basket[col] = np.where(~(basket[col].str.find(keyword) > -1), 0, 1)
    i += 1 

wneeded_basket.head()

,Age,Gender,Marital Status,Employment Status,Current Region,Frequency,Where,Apparel/Clothing,Health & Personal Care,Home Entertainment,...,Stationery,Books,Sports & Travel,Wearable Accessories,Automobile Accessories,Cameras/Camera Accessories,Laptops/Computers,Tech Accessories,Pet Care/Accessories,Power Tools
0,21,Male,Single,Employed,Region III - Central Luzon,2,Online Stores,1,1,1,...,0,0,0,1,0,0,0,0,0,0
1,21,Male,Single,Student,CAR - Cordillera Administrative Region,1,Online Stores,0,1,1,...,1,1,1,1,1,1,1,1,1,1
2,20,Male,Single,Student,Region III - Central Luzon,2,Online Stores,1,0,0,...,1,1,1,1,1,1,1,0,1,1
3,21,Female,Single,Student,Region IV-A - CALABARZON,4,Online Stores,0,0,1,...,1,1,1,0,0,0,1,1,1,0
4,22,Female,Single,Student,Region IV-A - CALABARZON,5,Online Stores,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
# Possible answers of respondents in survey (Also the items available for each season)
summer_items = ["Clothing", "Umbrellas", "Sunscreen/Heat-Protectant Skin Products", 
"Swimsuit", "Swim Cap", "Swim Goggles", "Swim Snorkles", "Towels", "Bags", "Water Bottles", 
"Ice Cooler", "Inflatable Pools", "Pool Toys", "Swimming Safety Equipment (Swimming Rings/Life Jacket/Floaties/Etc.)", "Electric Fan"]

bts_items = ["Pen/Marker/Pencil/Scriber", "Paper/Envelopes/Post-it Notes/", "Notebooks", 
"Academic Books", "Art Materials", "Laptop", "Phone/Tablet", "Tech Products/Tech Accessories", 
"School Uniforms/Clothing", "Umbrella", "Raincoat", "Bags/School Bags", "Make up/Beauty Products"]

In [33]:
# Create baskets according to season part 2
summer_basket = raw_df[user_data_cols]
bts_basket = raw_df[user_data_cols]

# Set appropriate columns
summer_basket = summer_basket.reindex(columns = summer_basket.columns.tolist() + summer_items)
bts_basket = bts_basket.reindex(columns = bts_basket.columns.tolist() + bts_items)

# Assign appropriate values in summer basket
for col in summer_basket.columns:
    if col not in user_data_cols:
        summer_basket[col] = np.where(~(raw_df["Summer"].str.find(col) > -1), 0, 1)
# Assign Appropriate Values in Back To School basket
for col in bts_basket.columns:
    if col not in user_data_cols:
        bts_basket[col] = np.where(~(raw_df["Back To School"].str.find(col) > -1), 0, 1)

# Clean column name
to_replace_summer = {
    "Swimming Safety Equipment (Swimming Rings/Life Jacket/Floaties/Etc.)":"Swimming Safety Equipment",
}
summer_basket.rename(columns = to_replace_summer, inplace = True)

summer_basket.head()

,Age,Gender,Marital Status,Employment Status,Current Region,Frequency,Where,Clothing,Umbrellas,Sunscreen/Heat-Protectant Skin Products,...,Swim Goggles,Swim Snorkles,Towels,Bags,Water Bottles,Ice Cooler,Inflatable Pools,Pool Toys,Swimming Safety Equipment,Electric Fan
0,21,Male,Single,Employed,Region III - Central Luzon,2,Online Stores,1,1,0,...,0,0,1,0,1,0,0,0,0,0
1,21,Male,Single,Student,CAR - Cordillera Administrative Region,1,Online Stores,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2,20,Male,Single,Student,Region III - Central Luzon,2,Online Stores,1,1,1,...,1,0,0,0,1,0,0,0,0,0
3,21,Female,Single,Student,Region IV-A - CALABARZON,4,Online Stores,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,22,Female,Single,Student,Region IV-A - CALABARZON,5,Online Stores,1,0,1,...,0,0,0,0,0,0,0,0,0,0

List of baskets created:

- holidays_basket (xmas, new year)

- bdays_basket (self/others)

- periods_basket (monthly/weekly/shopping sales)

- wneeded_basket (when needed)

- summer_basket (summer)

- bts_basket (back to school)

In [34]:
# Create a dataframe of all baskets
basket_names = ["holidays_basket", "bdays_basket", "periods_basket", "wneeded_basket", "summer_basket", "bts_basket"]
all_baskets = [holidays_basket, bdays_basket, periods_basket, wneeded_basket, summer_basket, bts_basket]
# initialize minimum supports for each basket here
min_supports = [0.05, 0.1, 0.05, 0.5, 0.1, 0.2]
baskets = pd.DataFrame({"name":basket_names,"basket":all_baskets, "min_support":min_supports})
baskets

,name,basket,min_support
0,holidays_basket,Age Gender Marital Status Employment Stat...,0.05
1,bdays_basket,Age Gender Marital Status Employment Stat...,0.10
2,periods_basket,Age Gender Marital Status Employment Stat...,0.05
3,wneeded_basket,Age Gender Marital Status Employment Stat...,0.50
4,summer_basket,Age Gender Marital Status Employment Stat...,0.10
5,bts_basket,Age Gender Marital Status Employment Stat...,0.20

## Get rules from all generalized baskets:

for i in baskets.index:
    # Indicate which basket to show rules:
    row = baskets.iloc[i]
    basket_name = row["name"]
    basket = row["basket"]
    min_support = row["min_support"]
    print(f'basket name: {basket_name}')

    # Sort the holiday basket
    # Sort the basket before dropping user_data_cols
    # Example: sort it such that only female respondents are left
    basket_sorted = basket.drop(user_data_cols, axis=1)

    # Get frequent item set
    freq_items = apriori(basket_sorted, min_support = min_support, use_colnames=True)
    freq_items.sort_values("support", ascending=False)

    print(f'length of frequent item sets: {len(freq_items)}')
    print(f'minimum support: {min_support}')
    # Get rules 
    rules = association_rules(freq_items, metric="lift", min_threshold=1)
    display(rules.sort_values("support", ascending=False).head(10))

In [35]:
basket.head()

,Age,Gender,Marital Status,Employment Status,Current Region,Frequency,Where,Apparel/Clothing,Health & Personal Care,Home Entertainment,...,Stationery,Books,Sports & Travel,Wearable Accessories,Automobile Accessories,Cameras/Camera Accessories,Laptops/Computers,Tech Accessories,Pet Care/Accessories,Power Tools
0,21,Male,Single,Employed,Region III - Central Luzon,2,Online Stores,1,1,1,...,0,0,0,1,0,0,0,0,0,0
1,21,Male,Single,Student,CAR - Cordillera Administrative Region,1,Online Stores,0,1,1,...,1,1,1,1,1,1,1,1,1,1
2,20,Male,Single,Student,Region III - Central Luzon,2,Online Stores,1,0,0,...,1,1,1,1,1,1,1,0,1,1
3,21,Female,Single,Student,Region IV-A - CALABARZON,4,Online Stores,0,0,1,...,1,1,1,0,0,0,1,1,1,0
4,22,Female,Single,Student,Region IV-A - CALABARZON,5,Online Stores,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [45]:
# Get rules from all baskets

for i in baskets.index:
    # Indicate which basket to show rules:
    row = baskets.iloc[i]
    basket_name = row["name"]
    basket = row["basket"]
    min_support = row["min_support"]
    print(f'basket name: {basket_name}')

    # Sort the holiday basket
    # Sort the basket before dropping user_data_cols
    basket_sorted = basket.drop(user_data_cols, axis=1)
    
    # Get frequent item set
    freq_items = apriori(basket_sorted, min_support = min_support, use_colnames=True)
    freq_items.sort_values("support", ascending=False)

    print(f'length of frequent item sets: {len(freq_items)}')
    print(f'minimum support: {min_support}')
    # Get rules 
    rules = association_rules(freq_items, metric="lift", min_threshold=1)
    display(rules.sort_values("support", ascending=False).head(10))

basket name: holidays_basket
length of frequent item sets: 35
minimum support: 0.05

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
15,(Apparel/Clothing),(Wearable Accessories),0.322917,0.197917,0.114583,0.354839,1.792869,0.050673,1.243229
14,(Wearable Accessories),(Apparel/Clothing),0.197917,0.322917,0.114583,0.578947,1.792869,0.050673,1.608073
12,(Sports & Travel),(Apparel/Clothing),0.125000,0.322917,0.093750,0.750000,2.322581,0.053385,2.708333
13,(Apparel/Clothing),(Sports & Travel),0.322917,0.125000,0.093750,0.290323,2.322581,0.053385,1.232955
36,(Bags),(Wearable Accessories),0.125000,0.197917,0.083333,0.666667,3.368421,0.058594,2.406250
37,(Wearable Accessories),(Bags),0.197917,0.125000,0.083333,0.421053,3.368421,0.058594,1.511364
8,(Bags),(Apparel/Clothing),0.125000,0.322917,0.083333,0.666667,2.064516,0.042969,2.031250
9,(Apparel/Clothing),(Bags),0.322917,0.125000,0.083333,0.258065,2.064516,0.042969,1.179348
11,(Apparel/Clothing),(Books),0.322917,0.083333,0.072917,0.225806,2.709677,0.046007,1.184028
42,"(Bags, Wearable Accessories)",(Apparel/Clothing),0.083333,0.322917,0.072917,0.875000,2.709677,0.046007,5.416667

basket name: bdays_basket
length of frequent item sets: 32
minimum support: 0.1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
6,(Wearable Accessories),(Apparel/Clothing),0.333333,0.312500,0.208333,0.625000,2.000000,0.104167,1.833333
7,(Apparel/Clothing),(Wearable Accessories),0.312500,0.333333,0.208333,0.666667,2.000000,0.104167,2.000000
15,(Wearable Accessories),"(Toys, Games, Collectibles)",0.333333,0.354167,0.177083,0.531250,1.500000,0.059028,1.377778
14,"(Toys, Games, Collectibles)",(Wearable Accessories),0.354167,0.333333,0.177083,0.500000,1.500000,0.059028,1.333333
19,"(Toys, Games, Collectibles)",(Tech Accessories),0.354167,0.260417,0.166667,0.470588,1.807059,0.074436,1.396991
18,(Tech Accessories),"(Toys, Games, Collectibles)",0.260417,0.354167,0.166667,0.640000,1.807059,0.074436,1.793981
21,(Wearable Accessories),(Bags),0.333333,0.229167,0.145833,0.437500,1.909091,0.069444,1.370370
20,(Bags),(Wearable Accessories),0.229167,0.333333,0.145833,0.636364,1.909091,0.069444,1.833333
35,(Laptops/Computers),(Tech Accessories),0.197917,0.260417,0.125000,0.631579,2.425263,0.073459,2.007440
34,(Tech Accessories),(Laptops/Computers),0.260417,0.197917,0.125000,0.480000,2.425263,0.073459,1.542468

basket name: periods_basket
length of frequent item sets: 35
minimum support: 0.05

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
8,(Health & Personal Care),(Food/Groceries),0.322917,0.510417,0.270833,0.838710,1.643186,0.106011,3.035417
9,(Food/Groceries),(Health & Personal Care),0.510417,0.322917,0.270833,0.530612,1.643186,0.106011,1.442482
2,(Food/Groceries),(Apparel/Clothing),0.510417,0.177083,0.135417,0.265306,1.498199,0.045030,1.120081
3,(Apparel/Clothing),(Food/Groceries),0.177083,0.510417,0.135417,0.764706,1.498199,0.045030,2.080729
14,(Home Entertainment),(Food/Groceries),0.145833,0.510417,0.093750,0.642857,1.259475,0.019314,1.370833
30,(Pet Care/Accessories),(Food/Groceries),0.125000,0.510417,0.093750,0.750000,1.469388,0.029948,1.958333
31,(Food/Groceries),(Pet Care/Accessories),0.510417,0.125000,0.093750,0.183673,1.469388,0.029948,1.071875
15,(Food/Groceries),(Home Entertainment),0.510417,0.145833,0.093750,0.183673,1.259475,0.019314,1.046354
13,(Health & Personal Care),(Pet Care/Accessories),0.322917,0.125000,0.072917,0.225806,1.806452,0.032552,1.130208
24,(Books),(Food/Groceries),0.114583,0.510417,0.072917,0.636364,1.246753,0.014431,1.346354

basket name: wneeded_basket
length of frequent item sets: 28
minimum support: 0.5

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
25,(Laptops/Computers),(Tech Accessories),0.760417,0.666667,0.572917,0.753425,1.130137,0.065972,1.351852
24,(Tech Accessories),(Laptops/Computers),0.666667,0.760417,0.572917,0.859375,1.130137,0.065972,1.703704
12,(Laptops/Computers),(Stationery),0.760417,0.677083,0.572917,0.753425,1.112750,0.058051,1.309606
13,(Stationery),(Laptops/Computers),0.677083,0.760417,0.572917,0.846154,1.112750,0.058051,1.557292
18,(Books),(Laptops/Computers),0.635417,0.760417,0.552083,0.868852,1.142600,0.068902,1.826823
19,(Laptops/Computers),(Books),0.760417,0.635417,0.552083,0.726027,1.142600,0.068902,1.330729
29,(Laptops/Computers),(Power Tools),0.760417,0.583333,0.541667,0.712329,1.221135,0.098090,1.448413
2,(Home Entertainment),(Laptops/Computers),0.625000,0.760417,0.541667,0.866667,1.139726,0.066406,1.796875
3,(Laptops/Computers),(Home Entertainment),0.760417,0.625000,0.541667,0.712329,1.139726,0.066406,1.303571
28,(Power Tools),(Laptops/Computers),0.583333,0.760417,0.541667,0.928571,1.221135,0.098090,3.354167

basket name: summer_basket
length of frequent item sets: 93
minimum support: 0.1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
7,(Water Bottles),(Clothing),0.531250,0.729167,0.395833,0.745098,1.021849,0.008464,1.062500
6,(Clothing),(Water Bottles),0.729167,0.531250,0.395833,0.542857,1.021849,0.008464,1.025391
26,(Water Bottles),(Sunscreen/Heat-Protectant Skin Products),0.531250,0.572917,0.385417,0.725490,1.266310,0.081055,1.555804
27,(Sunscreen/Heat-Protectant Skin Products),(Water Bottles),0.572917,0.531250,0.385417,0.672727,1.266310,0.081055,1.432292
2,(Clothing),(Towels),0.729167,0.416667,0.333333,0.457143,1.097143,0.029514,1.074561
3,(Towels),(Clothing),0.416667,0.729167,0.333333,0.800000,1.097143,0.029514,1.354167
23,(Sunscreen/Heat-Protectant Skin Products),(Towels),0.572917,0.416667,0.322917,0.563636,1.352727,0.084201,1.336806
22,(Towels),(Sunscreen/Heat-Protectant Skin Products),0.416667,0.572917,0.322917,0.775000,1.352727,0.084201,1.898148
36,(Water Bottles),(Towels),0.531250,0.416667,0.312500,0.588235,1.411765,0.091146,1.416667
37,(Towels),(Water Bottles),0.416667,0.531250,0.312500,0.750000,1.411765,0.091146,1.875000

basket name: bts_basket
length of frequent item sets: 244
minimum support: 0.2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
2,(Pen/Marker/Pencil/Scriber),(Notebooks),0.958333,0.885417,0.854167,0.891304,1.006650,0.005642,1.054167
3,(Notebooks),(Pen/Marker/Pencil/Scriber),0.885417,0.958333,0.854167,0.964706,1.006650,0.005642,1.180556
0,(Pen/Marker/Pencil/Scriber),(Paper/Envelopes/Post-it Notes/),0.958333,0.822917,0.802083,0.836957,1.017061,0.013455,1.086111
1,(Paper/Envelopes/Post-it Notes/),(Pen/Marker/Pencil/Scriber),0.822917,0.958333,0.802083,0.974684,1.017061,0.013455,1.645833
12,(Notebooks),(Paper/Envelopes/Post-it Notes/),0.885417,0.822917,0.729167,0.823529,1.000745,0.000543,1.003472
13,(Paper/Envelopes/Post-it Notes/),(Notebooks),0.822917,0.885417,0.729167,0.886076,1.000745,0.000543,1.005787
76,"(Pen/Marker/Pencil/Scriber, Notebooks)",(Paper/Envelopes/Post-it Notes/),0.854167,0.822917,0.708333,0.829268,1.007718,0.005425,1.037202
77,"(Paper/Envelopes/Post-it Notes/, Notebooks)",(Pen/Marker/Pencil/Scriber),0.729167,0.958333,0.708333,0.971429,1.013665,0.009549,1.458333
78,(Pen/Marker/Pencil/Scriber),"(Paper/Envelopes/Post-it Notes/, Notebooks)",0.958333,0.729167,0.708333,0.739130,1.013665,0.009549,1.038194
79,(Paper/Envelopes/Post-it Notes/),"(Pen/Marker/Pencil/Scriber, Notebooks)",0.822917,0.854167,0.708333,0.860759,1.007718,0.005425,1.047348

In [43]:
# Get rules from all male baskets

for i in baskets.index:
    # Indicate which basket to show rules:
    row = baskets.iloc[i]
    basket_name = row["name"]
    basket = row["basket"]
    min_support = row["min_support"]
    print(f'basket name: {basket_name}')

    # Sort the holiday basket
    # Sort the basket before dropping user_data_cols
    basket_sorted = basket[basket["Gender"] == "Male"].drop(user_data_cols, axis=1)
    
    # Get frequent item set
    freq_items = apriori(basket_sorted, min_support = min_support, use_colnames=True)
    freq_items.sort_values("support", ascending=False)

    print(f'length of frequent item sets: {len(freq_items)}')
    print(f'minimum support: {min_support}')
    # Get rules 
    rules = association_rules(freq_items, metric="lift", min_threshold=1)
    display(rules.sort_values("support", ascending=False).head(10))

basket name: holidays_basket
length of frequent item sets: 74
minimum support: 0.05

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
8,(Sports & Travel),(Apparel/Clothing),0.20,0.32,0.14,0.700000,2.187500,0.0760,2.266667
9,(Apparel/Clothing),(Sports & Travel),0.32,0.20,0.14,0.437500,2.187500,0.0760,1.422222
25,(Tech Accessories),(Home Entertainment),0.18,0.24,0.12,0.666667,2.777778,0.0768,2.280000
16,(Tech Accessories),(Apparel/Clothing),0.18,0.32,0.12,0.666667,2.083333,0.0624,2.040000
2,"(Toys, Games, Collectibles)",(Apparel/Clothing),0.26,0.32,0.12,0.461538,1.442308,0.0368,1.262857
3,(Apparel/Clothing),"(Toys, Games, Collectibles)",0.32,0.26,0.12,0.375000,1.442308,0.0368,1.184000
24,(Home Entertainment),(Tech Accessories),0.24,0.18,0.12,0.500000,2.777778,0.0768,1.640000
17,(Apparel/Clothing),(Tech Accessories),0.32,0.18,0.12,0.375000,2.083333,0.0624,1.312000
41,"(Toys, Games, Collectibles)",(Tech Accessories),0.26,0.18,0.10,0.384615,2.136752,0.0532,1.332500
40,(Tech Accessories),"(Toys, Games, Collectibles)",0.18,0.26,0.10,0.555556,2.136752,0.0532,1.665000

basket name: bdays_basket
length of frequent item sets: 71
minimum support: 0.1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
38,(Tech Accessories),"(Toys, Games, Collectibles)",0.34,0.46,0.24,0.705882,1.534527,0.0836,1.836000
39,"(Toys, Games, Collectibles)",(Tech Accessories),0.46,0.34,0.24,0.521739,1.534527,0.0836,1.380000
33,(Wearable Accessories),"(Toys, Games, Collectibles)",0.34,0.46,0.24,0.705882,1.534527,0.0836,1.836000
32,"(Toys, Games, Collectibles)",(Wearable Accessories),0.46,0.34,0.24,0.521739,1.534527,0.0836,1.380000
0,"(Toys, Games, Collectibles)",(Apparel/Clothing),0.46,0.30,0.20,0.434783,1.449275,0.0620,1.238462
6,(Wearable Accessories),(Apparel/Clothing),0.34,0.30,0.20,0.588235,1.960784,0.0980,1.700000
7,(Apparel/Clothing),(Wearable Accessories),0.30,0.34,0.20,0.666667,1.960784,0.0980,1.980000
1,(Apparel/Clothing),"(Toys, Games, Collectibles)",0.30,0.46,0.20,0.666667,1.449275,0.0620,1.620000
60,(Laptops/Computers),(Wearable Accessories),0.28,0.34,0.18,0.642857,1.890756,0.0848,1.848000
61,(Wearable Accessories),(Laptops/Computers),0.34,0.28,0.18,0.529412,1.890756,0.0848,1.530000

basket name: periods_basket
length of frequent item sets: 73
minimum support: 0.05

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
12,(Health & Personal Care),(Food/Groceries),0.24,0.54,0.22,0.916667,1.697531,0.0904,5.520000
13,(Food/Groceries),(Health & Personal Care),0.54,0.24,0.22,0.407407,1.697531,0.0904,1.282500
2,(Food/Groceries),(Apparel/Clothing),0.54,0.16,0.12,0.222222,1.388889,0.0336,1.080000
3,(Apparel/Clothing),(Food/Groceries),0.16,0.54,0.12,0.750000,1.388889,0.0336,1.840000
40,(Pet Care/Accessories),(Food/Groceries),0.14,0.54,0.12,0.857143,1.587302,0.0444,3.220000
41,(Food/Groceries),(Pet Care/Accessories),0.54,0.14,0.12,0.222222,1.587302,0.0444,1.105714
19,(Food/Groceries),(Home Entertainment),0.54,0.18,0.12,0.222222,1.234568,0.0228,1.054286
18,(Home Entertainment),(Food/Groceries),0.18,0.54,0.12,0.666667,1.234568,0.0228,1.380000
32,(Books),(Food/Groceries),0.16,0.54,0.10,0.625000,1.157407,0.0136,1.226667
33,(Food/Groceries),(Books),0.54,0.16,0.10,0.185185,1.157407,0.0136,1.030909

basket name: wneeded_basket
length of frequent item sets: 36
minimum support: 0.5

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
10,(Laptops/Computers),(Health & Personal Care),0.78,0.72,0.62,0.794872,1.103989,0.0584,1.365000
11,(Health & Personal Care),(Laptops/Computers),0.72,0.78,0.62,0.861111,1.103989,0.0584,1.584000
39,(Laptops/Computers),(Tech Accessories),0.78,0.70,0.60,0.769231,1.098901,0.0540,1.300000
20,(Bags),(Laptops/Computers),0.72,0.78,0.60,0.833333,1.068376,0.0384,1.320000
21,(Laptops/Computers),(Bags),0.78,0.72,0.60,0.769231,1.068376,0.0384,1.213333
38,(Tech Accessories),(Laptops/Computers),0.70,0.78,0.60,0.857143,1.098901,0.0540,1.540000
23,(Tech Accessories),(Bags),0.70,0.72,0.58,0.828571,1.150794,0.0760,1.633333
22,(Bags),(Tech Accessories),0.72,0.70,0.58,0.805556,1.150794,0.0760,1.542857
19,(Books),(Bags),0.64,0.72,0.56,0.875000,1.215278,0.0992,2.240000
5,(Apparel/Clothing),(Laptops/Computers),0.64,0.78,0.56,0.875000,1.121795,0.0608,1.760000

basket name: summer_basket
length of frequent item sets: 88
minimum support: 0.1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
6,(Clothing),(Water Bottles),0.74,0.56,0.42,0.567568,1.013514,0.0056,1.017500
7,(Water Bottles),(Clothing),0.56,0.74,0.42,0.750000,1.013514,0.0056,1.040000
28,(Water Bottles),(Sunscreen/Heat-Protectant Skin Products),0.56,0.42,0.36,0.642857,1.530612,0.1248,1.624000
29,(Sunscreen/Heat-Protectant Skin Products),(Water Bottles),0.42,0.56,0.36,0.857143,1.530612,0.1248,3.080000
2,(Clothing),(Towels),0.74,0.40,0.34,0.459459,1.148649,0.0440,1.110000
3,(Towels),(Clothing),0.40,0.74,0.34,0.850000,1.148649,0.0440,1.733333
37,(Towels),(Water Bottles),0.40,0.56,0.32,0.800000,1.428571,0.0960,2.200000
36,(Water Bottles),(Towels),0.56,0.40,0.32,0.571429,1.428571,0.0960,1.400000
0,(Clothing),(Umbrellas),0.74,0.36,0.28,0.378378,1.051051,0.0136,1.029565
1,(Umbrellas),(Clothing),0.36,0.74,0.28,0.777778,1.051051,0.0136,1.170000

basket name: bts_basket
length of frequent item sets: 259
minimum support: 0.2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
2,(Pen/Marker/Pencil/Scriber),(Notebooks),0.94,0.86,0.82,0.872340,1.014349,0.0116,1.096667
3,(Notebooks),(Pen/Marker/Pencil/Scriber),0.86,0.94,0.82,0.953488,1.014349,0.0116,1.290000
0,(Pen/Marker/Pencil/Scriber),(Paper/Envelopes/Post-it Notes/),0.94,0.74,0.72,0.765957,1.035078,0.0244,1.110909
1,(Paper/Envelopes/Post-it Notes/),(Pen/Marker/Pencil/Scriber),0.74,0.94,0.72,0.972973,1.035078,0.0244,2.220000
11,(Paper/Envelopes/Post-it Notes/),(Notebooks),0.74,0.86,0.64,0.864865,1.005657,0.0036,1.036000
10,(Notebooks),(Paper/Envelopes/Post-it Notes/),0.86,0.74,0.64,0.744186,1.005657,0.0036,1.016364
84,(Notebooks),"(Pen/Marker/Pencil/Scriber, Paper/Envelopes/Po...",0.86,0.72,0.62,0.720930,1.001292,0.0008,1.003333
83,(Pen/Marker/Pencil/Scriber),"(Paper/Envelopes/Post-it Notes/, Notebooks)",0.94,0.64,0.62,0.659574,1.030585,0.0184,1.057500
82,"(Paper/Envelopes/Post-it Notes/, Notebooks)",(Pen/Marker/Pencil/Scriber),0.64,0.94,0.62,0.968750,1.030585,0.0184,1.920000
81,"(Pen/Marker/Pencil/Scriber, Paper/Envelopes/Po...",(Notebooks),0.72,0.86,0.62,0.861111,1.001292,0.0008,1.008000

In [38]:
# Get rules from all female baskets

for i in baskets.index:
    # Indicate which basket to show rules:
    row = baskets.iloc[i]
    basket_name = row["name"]
    basket = row["basket"]
    min_support = row["min_support"]
    print(f'basket name: {basket_name}')

    # Sort the holiday basket
    # Sort the basket before dropping user_data_cols
    basket_sorted = basket[basket["Gender"] == "Female"].drop(user_data_cols, axis=1)
    
    # Get frequent item set
    freq_items = apriori(basket_sorted, min_support = min_support, use_colnames=True)
    freq_items.sort_values("support", ascending=False)

    print(f'length of frequent item sets: {len(freq_items)}')
    print(f'minimum support: {min_support}')
    # Get rules 
    rules = association_rules(freq_items, metric="lift", min_threshold=1)
    display(rules.sort_values("support", ascending=False).head(10))

basket name: holidays_basket
length of frequent item sets: 23
minimum support: 0.05

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
8,(Wearable Accessories),(Apparel/Clothing),0.204545,0.318182,0.136364,0.666667,2.095238,0.071281,2.045455
9,(Apparel/Clothing),(Wearable Accessories),0.318182,0.204545,0.136364,0.428571,2.095238,0.071281,1.392045
35,(Bags),"(Wearable Accessories, Apparel/Clothing)",0.159091,0.136364,0.113636,0.714286,5.238095,0.091942,3.022727
36,(Wearable Accessories),"(Bags, Apparel/Clothing)",0.204545,0.113636,0.113636,0.555556,4.888889,0.090393,1.994318
17,(Wearable Accessories),(Bags),0.204545,0.159091,0.113636,0.555556,3.492063,0.081095,1.892045
16,(Bags),(Wearable Accessories),0.159091,0.204545,0.113636,0.714286,3.492063,0.081095,2.784091
37,(Apparel/Clothing),"(Bags, Wearable Accessories)",0.318182,0.113636,0.113636,0.357143,3.142857,0.077479,1.378788
6,(Bags),(Apparel/Clothing),0.159091,0.318182,0.113636,0.714286,2.244898,0.063017,2.386364
7,(Apparel/Clothing),(Bags),0.318182,0.159091,0.113636,0.357143,2.244898,0.063017,1.308081
34,"(Wearable Accessories, Apparel/Clothing)",(Bags),0.136364,0.159091,0.113636,0.833333,5.238095,0.091942,5.045455

basket name: bdays_basket
length of frequent item sets: 18
minimum support: 0.1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
5,(Apparel/Clothing),(Wearable Accessories),0.340909,0.340909,0.227273,0.666667,1.955556,0.111054,1.977273
4,(Wearable Accessories),(Apparel/Clothing),0.340909,0.340909,0.227273,0.666667,1.955556,0.111054,1.977273
0,(Bags),(Apparel/Clothing),0.272727,0.340909,0.181818,0.666667,1.955556,0.088843,1.977273
11,(Wearable Accessories),(Bags),0.340909,0.272727,0.181818,0.533333,1.955556,0.088843,1.558442
1,(Apparel/Clothing),(Bags),0.340909,0.272727,0.181818,0.533333,1.955556,0.088843,1.558442
10,(Bags),(Wearable Accessories),0.272727,0.340909,0.181818,0.666667,1.955556,0.088843,1.977273
3,(Apparel/Clothing),(Books),0.340909,0.250000,0.136364,0.400000,1.600000,0.051136,1.250000
2,(Books),(Apparel/Clothing),0.250000,0.340909,0.136364,0.545455,1.600000,0.051136,1.450000
14,"(Bags, Wearable Accessories)",(Apparel/Clothing),0.181818,0.340909,0.136364,0.750000,2.200000,0.074380,2.636364
15,"(Bags, Apparel/Clothing)",(Wearable Accessories),0.181818,0.340909,0.136364,0.750000,2.200000,0.074380,2.636364

basket name: periods_basket
length of frequent item sets: 26
minimum support: 0.05

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
8,(Health & Personal Care),(Food/Groceries),0.409091,0.454545,0.318182,0.777778,1.711111,0.132231,2.454545
9,(Food/Groceries),(Health & Personal Care),0.454545,0.409091,0.318182,0.700000,1.711111,0.132231,1.969697
2,(Food/Groceries),(Apparel/Clothing),0.454545,0.204545,0.159091,0.350000,1.711111,0.066116,1.223776
3,(Apparel/Clothing),(Food/Groceries),0.204545,0.454545,0.159091,0.777778,1.711111,0.066116,2.454545
0,(Health & Personal Care),(Apparel/Clothing),0.409091,0.204545,0.136364,0.333333,1.629630,0.052686,1.193182
1,(Apparel/Clothing),(Health & Personal Care),0.204545,0.409091,0.136364,0.666667,1.629630,0.052686,1.772727
24,(Health & Personal Care),"(Apparel/Clothing, Food/Groceries)",0.409091,0.159091,0.113636,0.277778,1.746032,0.048554,1.164336
23,(Food/Groceries),"(Health & Personal Care, Apparel/Clothing)",0.454545,0.136364,0.113636,0.250000,1.833333,0.051653,1.151515
22,"(Health & Personal Care, Apparel/Clothing)",(Food/Groceries),0.136364,0.454545,0.113636,0.833333,1.833333,0.051653,3.272727
21,"(Apparel/Clothing, Food/Groceries)",(Health & Personal Care),0.159091,0.409091,0.113636,0.714286,1.746032,0.048554,2.068182

basket name: wneeded_basket
length of frequent item sets: 67
minimum support: 0.5

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
8,(Home Entertainment),(Laptops/Computers),0.681818,0.727273,0.613636,0.900000,1.237500,0.117769,2.727273
9,(Laptops/Computers),(Home Entertainment),0.727273,0.681818,0.613636,0.843750,1.237500,0.117769,2.036364
63,(Laptops/Computers),(Power Tools),0.727273,0.613636,0.613636,0.843750,1.375000,0.167355,2.472727
62,(Power Tools),(Laptops/Computers),0.613636,0.727273,0.613636,1.000000,1.375000,0.167355,inf
52,(Laptops/Computers),(Cameras/Camera Accessories),0.727273,0.659091,0.613636,0.843750,1.280172,0.134298,2.181818
53,(Cameras/Camera Accessories),(Laptops/Computers),0.659091,0.727273,0.613636,0.931034,1.280172,0.134298,3.954545
37,(Laptops/Computers),(Sports & Travel),0.727273,0.659091,0.613636,0.843750,1.280172,0.134298,2.181818
36,(Sports & Travel),(Laptops/Computers),0.659091,0.727273,0.613636,0.931034,1.280172,0.134298,3.954545
21,(Stationery),(Laptops/Computers),0.681818,0.727273,0.590909,0.866667,1.191667,0.095041,2.045455
20,(Laptops/Computers),(Stationery),0.727273,0.681818,0.590909,0.812500,1.191667,0.095041,1.696970

basket name: summer_basket
length of frequent item sets: 112
minimum support: 0.1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Clothing),(Sunscreen/Heat-Protectant Skin Products),0.704545,0.750000,0.568182,0.806452,1.075269,0.039773,1.291667
1,(Sunscreen/Heat-Protectant Skin Products),(Clothing),0.750000,0.704545,0.568182,0.757576,1.075269,0.039773,1.218750
12,(Umbrellas),(Sunscreen/Heat-Protectant Skin Products),0.590909,0.750000,0.477273,0.807692,1.076923,0.034091,1.300000
13,(Sunscreen/Heat-Protectant Skin Products),(Umbrellas),0.750000,0.590909,0.477273,0.636364,1.076923,0.034091,1.125000
29,(Sunscreen/Heat-Protectant Skin Products),(Water Bottles),0.750000,0.522727,0.431818,0.575758,1.101449,0.039773,1.125000
28,(Water Bottles),(Sunscreen/Heat-Protectant Skin Products),0.522727,0.750000,0.431818,0.826087,1.101449,0.039773,1.437500
25,(Sunscreen/Heat-Protectant Skin Products),(Towels),0.750000,0.431818,0.386364,0.515152,1.192982,0.062500,1.171875
24,(Towels),(Sunscreen/Heat-Protectant Skin Products),0.431818,0.750000,0.386364,0.894737,1.192982,0.062500,2.375000
8,(Clothing),(Water Bottles),0.704545,0.522727,0.386364,0.548387,1.049088,0.018079,1.056818
9,(Water Bottles),(Clothing),0.522727,0.704545,0.386364,0.739130,1.049088,0.018079,1.132576

basket name: bts_basket
length of frequent item sets: 440
minimum support: 0.2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
11,(Bags/School Bags),(Pen/Marker/Pencil/Scriber),0.636364,0.977273,0.636364,1.000000,1.023256,0.014463,inf
10,(Pen/Marker/Pencil/Scriber),(Bags/School Bags),0.977273,0.636364,0.636364,0.651163,1.023256,0.014463,1.042424
157,"(Pen/Marker/Pencil/Scriber, Bags/School Bags)",(Notebooks),0.636364,0.931818,0.613636,0.964286,1.034843,0.020661,1.909091
156,"(Pen/Marker/Pencil/Scriber, Notebooks)",(Bags/School Bags),0.909091,0.636364,0.613636,0.675000,1.060714,0.035124,1.118881
33,(Notebooks),(Bags/School Bags),0.931818,0.636364,0.613636,0.658537,1.034843,0.020661,1.064935
158,"(Bags/School Bags, Notebooks)",(Pen/Marker/Pencil/Scriber),0.613636,0.977273,0.613636,1.000000,1.023256,0.013946,inf
159,(Pen/Marker/Pencil/Scriber),"(Bags/School Bags, Notebooks)",0.977273,0.613636,0.613636,0.627907,1.023256,0.013946,1.038352
160,(Notebooks),"(Pen/Marker/Pencil/Scriber, Bags/School Bags)",0.931818,0.636364,0.613636,0.658537,1.034843,0.020661,1.064935
161,(Bags/School Bags),"(Pen/Marker/Pencil/Scriber, Notebooks)",0.636364,0.909091,0.613636,0.964286,1.060714,0.035124,2.545455
21,(Paper/Envelopes/Post-it Notes/),(Umbrella),0.909091,0.659091,0.613636,0.675000,1.024138,0.014463,1.048951

In [39]:
basket.columns

Index(['Age', 'Gender', 'Marital Status', 'Employment Status',
       'Current Region', 'Frequency', 'Where', 'Pen/Marker/Pencil/Scriber',
       'Paper/Envelopes/Post-it Notes/', 'Notebooks', 'Academic Books',
       'Art Materials', 'Laptop', 'Phone/Tablet',
       'Tech Products/Tech Accessories', 'School Uniforms/Clothing',
       'Umbrella', 'Raincoat', 'Bags/School Bags', 'Make up/Beauty Products'],
      dtype='object')

In [40]:
# Get rules from Region I - Ilocos Region

for i in baskets.index:
    # Indicate which basket to show rules:
    row = baskets.iloc[i]
    basket_name = row["name"]
    basket = row["basket"]
    min_support = row["min_support"]
    print(f'basket name: {basket_name}')
    # Sort the holiday basket
    # Sort the basket before dropping user_data_cols
    basket_sorted = basket[basket["Current Region"] == "Region I - Ilocos Region"].drop(user_data_cols, axis=1)
    
    # Get frequent item set
    freq_items = apriori(basket_sorted, min_support = min_support, use_colnames=True)
    freq_items.sort_values("support", ascending=False)

    print(f'length of frequent item sets: {len(freq_items)}')
    print(f'minimum support: {min_support}')
    # Get rules 
    rules = association_rules(freq_items, metric="lift", min_threshold=1)
    display(rules.sort_values("support", ascending=False).head(10))

basket name: holidays_basket
length of frequent item sets: 101
minimum support: 0.05

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
24,(Sports & Travel),(Food/Groceries),0.200000,0.142857,0.142857,0.714286,5.000000,0.114286,3.000000
25,(Food/Groceries),(Sports & Travel),0.142857,0.200000,0.142857,1.000000,5.000000,0.114286,inf
8,(Sports & Travel),(Apparel/Clothing),0.200000,0.285714,0.114286,0.571429,2.000000,0.057143,1.666667
9,(Apparel/Clothing),(Sports & Travel),0.285714,0.200000,0.114286,0.400000,2.000000,0.057143,1.333333
56,(Sports & Travel),(Wearable Accessories),0.200000,0.257143,0.114286,0.571429,2.222222,0.062857,1.733333
57,(Wearable Accessories),(Sports & Travel),0.257143,0.200000,0.114286,0.444444,2.222222,0.062857,1.440000
76,"(Sports & Travel, Food/Groceries)",(Apparel/Clothing),0.142857,0.285714,0.085714,0.600000,2.100000,0.044898,1.785714
77,"(Sports & Travel, Apparel/Clothing)",(Food/Groceries),0.114286,0.142857,0.085714,0.750000,5.250000,0.069388,3.428571
78,"(Apparel/Clothing, Food/Groceries)",(Sports & Travel),0.085714,0.200000,0.085714,1.000000,5.000000,0.068571,inf
0,(Food/Groceries),(Apparel/Clothing),0.142857,0.285714,0.085714,0.600000,2.100000,0.044898,1.785714

basket name: bdays_basket
length of frequent item sets: 47
minimum support: 0.1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
11,(Apparel/Clothing),(Wearable Accessories),0.314286,0.428571,0.285714,0.909091,2.121212,0.151020,6.285714
10,(Wearable Accessories),(Apparel/Clothing),0.428571,0.314286,0.285714,0.666667,2.121212,0.151020,2.057143
22,"(Toys, Games, Collectibles)",(Wearable Accessories),0.371429,0.428571,0.228571,0.615385,1.435897,0.069388,1.485714
23,(Wearable Accessories),"(Toys, Games, Collectibles)",0.428571,0.371429,0.228571,0.533333,1.435897,0.069388,1.346939
26,(Tech Accessories),"(Toys, Games, Collectibles)",0.228571,0.371429,0.200000,0.875000,2.355769,0.115102,5.028571
27,"(Toys, Games, Collectibles)",(Tech Accessories),0.371429,0.228571,0.200000,0.538462,2.355769,0.115102,1.671429
72,"(Books, Wearable Accessories)",(Apparel/Clothing),0.142857,0.314286,0.142857,1.000000,3.181818,0.097959,inf
24,(Laptops/Computers),"(Toys, Games, Collectibles)",0.228571,0.371429,0.142857,0.625000,1.682692,0.057959,1.676190
25,"(Toys, Games, Collectibles)",(Laptops/Computers),0.371429,0.228571,0.142857,0.384615,1.682692,0.057959,1.253571
28,(Bags),(Wearable Accessories),0.200000,0.428571,0.142857,0.714286,1.666667,0.057143,2.000000

basket name: periods_basket
length of frequent item sets: 73
minimum support: 0.05

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
15,(Food/Groceries),(Health & Personal Care),0.571429,0.400000,0.371429,0.650000,1.625000,0.142857,1.714286
14,(Health & Personal Care),(Food/Groceries),0.400000,0.571429,0.371429,0.928571,1.625000,0.142857,6.000000
4,(Food/Groceries),(Apparel/Clothing),0.571429,0.200000,0.142857,0.250000,1.250000,0.028571,1.066667
5,(Apparel/Clothing),(Food/Groceries),0.200000,0.571429,0.142857,0.714286,1.250000,0.028571,1.500000
0,(Health & Personal Care),(Apparel/Clothing),0.400000,0.200000,0.114286,0.285714,1.428571,0.034286,1.120000
80,"(Health & Personal Care, Apparel/Clothing)",(Food/Groceries),0.114286,0.571429,0.114286,1.000000,1.750000,0.048980,inf
78,"(Health & Personal Care, Food/Groceries)",(Apparel/Clothing),0.371429,0.200000,0.114286,0.307692,1.538462,0.040000,1.155556
79,"(Apparel/Clothing, Food/Groceries)",(Health & Personal Care),0.142857,0.400000,0.114286,0.800000,2.000000,0.057143,3.000000
81,(Food/Groceries),"(Health & Personal Care, Apparel/Clothing)",0.571429,0.114286,0.114286,0.200000,1.750000,0.048980,1.107143
82,(Health & Personal Care),"(Apparel/Clothing, Food/Groceries)",0.400000,0.142857,0.114286,0.285714,2.000000,0.057143,1.200000

basket name: wneeded_basket
length of frequent item sets: 106
minimum support: 0.5

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
68,(Tech Accessories),(Laptops/Computers),0.771429,0.828571,0.714286,0.925926,1.117497,0.075102,2.314286
69,(Laptops/Computers),(Tech Accessories),0.828571,0.771429,0.714286,0.862069,1.117497,0.075102,1.657143
77,(Tech Accessories),(Power Tools),0.771429,0.742857,0.685714,0.888889,1.196581,0.112653,2.314286
76,(Power Tools),(Tech Accessories),0.742857,0.771429,0.685714,0.923077,1.196581,0.112653,2.971429
73,(Laptops/Computers),(Power Tools),0.828571,0.742857,0.685714,0.827586,1.114058,0.070204,1.491429
72,(Power Tools),(Laptops/Computers),0.742857,0.828571,0.685714,0.923077,1.114058,0.070204,2.228571
276,(Tech Accessories),"(Power Tools, Laptops/Computers)",0.771429,0.685714,0.657143,0.851852,1.242284,0.128163,2.121429
60,(Laptops/Computers),(Cameras/Camera Accessories),0.828571,0.714286,0.657143,0.793103,1.110345,0.065306,1.380952
61,(Cameras/Camera Accessories),(Laptops/Computers),0.714286,0.828571,0.657143,0.920000,1.110345,0.065306,2.142857
62,(Tech Accessories),(Cameras/Camera Accessories),0.771429,0.714286,0.657143,0.851852,1.192593,0.106122,1.928571

basket name: summer_basket
length of frequent item sets: 215
minimum support: 0.1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
6,(Clothing),(Water Bottles),0.771429,0.714286,0.571429,0.740741,1.037037,0.020408,1.102041
7,(Water Bottles),(Clothing),0.714286,0.771429,0.571429,0.800000,1.037037,0.020408,1.142857
43,(Towels),(Water Bottles),0.571429,0.714286,0.514286,0.900000,1.260000,0.106122,2.857143
42,(Water Bottles),(Towels),0.714286,0.571429,0.514286,0.720000,1.260000,0.106122,1.530612
31,(Sunscreen/Heat-Protectant Skin Products),(Water Bottles),0.600000,0.714286,0.514286,0.857143,1.200000,0.085714,2.000000
30,(Water Bottles),(Sunscreen/Heat-Protectant Skin Products),0.714286,0.600000,0.514286,0.720000,1.200000,0.085714,1.428571
0,(Clothing),(Sunscreen/Heat-Protectant Skin Products),0.771429,0.600000,0.485714,0.629630,1.049383,0.022857,1.080000
1,(Sunscreen/Heat-Protectant Skin Products),(Clothing),0.600000,0.771429,0.485714,0.809524,1.049383,0.022857,1.200000
26,(Towels),(Sunscreen/Heat-Protectant Skin Products),0.571429,0.600000,0.428571,0.750000,1.250000,0.085714,1.600000
27,(Sunscreen/Heat-Protectant Skin Products),(Towels),0.600000,0.571429,0.428571,0.714286,1.250000,0.085714,1.500000

basket name: bts_basket
length of frequent item sets: 833
minimum support: 0.2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Pen/Marker/Pencil/Scriber),(Paper/Envelopes/Post-it Notes/),0.942857,0.828571,0.800000,0.848485,1.024033,0.018776,1.131429
1,(Paper/Envelopes/Post-it Notes/),(Pen/Marker/Pencil/Scriber),0.828571,0.942857,0.800000,0.965517,1.024033,0.018776,1.657143
28,(Umbrella),(Notebooks),0.714286,0.914286,0.714286,1.000000,1.093750,0.061224,inf
82,"(Pen/Marker/Pencil/Scriber, Notebooks)",(Paper/Envelopes/Post-it Notes/),0.857143,0.828571,0.714286,0.833333,1.005747,0.004082,1.028571
83,"(Paper/Envelopes/Post-it Notes/, Notebooks)",(Pen/Marker/Pencil/Scriber),0.742857,0.942857,0.714286,0.961538,1.019814,0.013878,1.485714
84,(Pen/Marker/Pencil/Scriber),"(Paper/Envelopes/Post-it Notes/, Notebooks)",0.942857,0.742857,0.714286,0.757576,1.019814,0.013878,1.060714
85,(Paper/Envelopes/Post-it Notes/),"(Pen/Marker/Pencil/Scriber, Notebooks)",0.828571,0.857143,0.714286,0.862069,1.005747,0.004082,1.035714
29,(Notebooks),(Umbrella),0.914286,0.714286,0.714286,0.781250,1.093750,0.061224,1.306122
30,(Bags/School Bags),(Notebooks),0.714286,0.914286,0.685714,0.960000,1.050000,0.032653,2.142857
31,(Notebooks),(Bags/School Bags),0.914286,0.714286,0.685714,0.750000,1.050000,0.032653,1.142857